/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edittxt;



import java.awt.Color;
import java.awt.GraphicsEnvironment;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JColorChooser;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;


/**
 *
 * @author Monchy
 */
public class Editor extends javax.swing.JFrame {

    /**
     * Creates new form Editor
     */
    public Editor() {
        initComponents();
        dc = text_pane.getStyledDocument();
        est = text_pane.addStyle("newEst",null);
        
        DefaultComboBoxModel modelo=(DefaultComboBoxModel)letra_tipo.getModel();
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String fontNames[] = ge.getAvailableFontFamilyNames();
        for(int i = 0; i<fontNames.length;i++){
            modelo.addElement(fontNames[i]);
        }letra_tipo.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_pane = new javax.swing.JTextPane();
        jToolBar1 = new javax.swing.JToolBar();
        letra_tipo = new javax.swing.JComboBox<>();
        combotamano = new javax.swing.JComboBox<>();
        btnegrta = new javax.swing.JButton();
        bttcursiva = new javax.swing.JButton();
        btsubra = new javax.swing.JButton();
        colorfont = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        text_pane.setBorder(null);
        text_pane.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        text_pane.setToolTipText("");
        jScrollPane1.setViewportView(text_pane);

        jToolBar1.setBackground(new java.awt.Color(153, 153, 255));
        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(450, 25));

        letra_tipo.setPreferredSize(new java.awt.Dimension(250, 24));
        letra_tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                letra_tipoItemStateChanged(evt);
            }
        });
        letra_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                letra_tipoActionPerformed(evt);
            }
        });
        jToolBar1.add(letra_tipo);

        combotamano.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "14", "16", "22", "28", "36" }));
        combotamano.setMinimumSize(new java.awt.Dimension(5, 22));
        combotamano.setPreferredSize(new java.awt.Dimension(50, 23));
        combotamano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                combotamanoMouseClicked(evt);
            }
        });
        combotamano.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combotamanoActionPerformed(evt);
            }
        });
        jToolBar1.add(combotamano);

        btnegrta.setBackground(new java.awt.Color(153, 153, 255));
        btnegrta.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        btnegrta.setText("N");
        btnegrta.setBorder(null);
        btnegrta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnegrtaMouseClicked(evt);
            }
        });
        btnegrta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnegrtaActionPerformed(evt);
            }
        });

        bttcursiva.setBackground(new java.awt.Color(153, 153, 255));
        bttcursiva.setFont(new java.awt.Font("Arial Black", 2, 24)); // NOI18N
        bttcursiva.setText("K");
        bttcursiva.setBorder(null);
        bttcursiva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bttcursivaMouseClicked(evt);
            }
        });
        bttcursiva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttcursivaActionPerformed(evt);
            }
        });

        btsubra.setBackground(new java.awt.Color(153, 153, 255));
        btsubra.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        btsubra.setText("S");
        btsubra.setBorder(null);
        btsubra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btsubraMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btsubraMouseEntered(evt);
            }
        });
        btsubra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsubraActionPerformed(evt);
            }
        });

        colorfont.setBackground(new java.awt.Color(153, 153, 255));
        colorfont.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IMGCOLL.png"))); // NOI18N
        colorfont.setBorder(null);
        colorfont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorfontMouseClicked(evt);
            }
        });
        colorfont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorfontActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/foldersgreendocuments_carpetas_verd_10970.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 0, 12)); // NOI18N
        jLabel1.setText("Abrir desde internet.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(colorfont, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnegrta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bttcursiva, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btsubra, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(37, 37, 37))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(colorfont, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(11, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnegrta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bttcursiva, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btsubra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttcursivaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttcursivaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bttcursivaActionPerformed

    private void btsubraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsubraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btsubraActionPerformed

    private void btnegrtaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnegrtaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnegrtaActionPerformed

    private void colorfontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorfontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorfontActionPerformed

    private void colorfontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colorfontMouseClicked
      try{
          StyleConstants.setForeground(est,
             JColorChooser.showDialog(this,
                     "Seleccione el color",Color.red)
            );
         
          
          dc.setCharacterAttributes(text_pane.getSelectionStart(),
                  text_pane.getSelectionEnd()- text_pane.getSelectionStart(),
                  text_pane.getStyle("newEst"), true);
          
      }catch(Exception e){
          System.out.println("Ya te llevo putas chavarría");
      }
        

    }//GEN-LAST:event_colorfontMouseClicked

    private void btnegrtaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnegrtaMouseClicked
           try{
               StyleConstants.setBold(est,true);
               
               dc.setCharacterAttributes(text_pane.getSelectionStart(), 
                       text_pane.getSelectionEnd()-text_pane.getSelectionStart(),
                       text_pane.getStyle("newEst"),true);
               
               
           }catch(Exception e){
                System.out.println("Ya te llevo putas chavarría");
            }
    }//GEN-LAST:event_btnegrtaMouseClicked

    private void bttcursivaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bttcursivaMouseClicked
        try{
            StyleConstants.setItalic(est,true);
            
            dc.setCharacterAttributes(text_pane.getSelectionStart(),
                    text_pane.getSelectionEnd()-text_pane.getSelectionStart(),
                    text_pane.getStyle("newEst"),true);
        }catch(Exception e){
            System.out.println("Ya te llevo putas chavarría");
        }
    }//GEN-LAST:event_bttcursivaMouseClicked

    private void btsubraMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsubraMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btsubraMouseEntered

    private void btsubraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btsubraMouseClicked
        try{
            StyleConstants.setUnderline(est,true);
            
            dc.setCharacterAttributes(text_pane.getSelectionStart(),
                    text_pane.getSelectionEnd()-text_pane.getSelectionStart(),
                    text_pane.getStyle("newEst"), true);
           
        }catch(Exception e){
            System.out.println("Ya te llevo putas chavarría");
        }
    }//GEN-LAST:event_btsubraMouseClicked

    private void combotamanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combotamanoMouseClicked
        
        
    }//GEN-LAST:event_combotamanoMouseClicked

    private void combotamanoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combotamanoActionPerformed
       StyleConstants.setFontSize(est,Integer.parseInt(combotamano.getSelectedItem().toString()));
        
        dc.setCharacterAttributes(text_pane.getSelectionStart(),
                text_pane.getSelectionEnd()-text_pane.getSelectionStart(), 
                text_pane.getStyle("newEst"),true
            ); 
    }//GEN-LAST:event_combotamanoActionPerformed

    private void letra_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_letra_tipoActionPerformed
       
        
        
        
    }//GEN-LAST:event_letra_tipoActionPerformed

    private void letra_tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_letra_tipoItemStateChanged
        
        StyleConstants.setFontFamily(est,letra_tipo.getSelectedItem().toString());
        
        dc.setCharacterAttributes(text_pane.getSelectionStart(),
                text_pane.getSelectionEnd()-text_pane.getSelectionStart(),
                text_pane.getStyle("newEst"),true);
        
        
        
        
    }//GEN-LAST:event_letra_tipoItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Editor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Editor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnegrta;
    private javax.swing.JButton btsubra;
    private javax.swing.JButton bttcursiva;
    private javax.swing.JButton colorfont;
    private javax.swing.JComboBox<String> combotamano;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JComboBox<String> letra_tipo;
    private javax.swing.JTextPane text_pane;
    // End of variables declaration//GEN-END:variables

StyledDocument dc;
Style est;

}
